# Generated by Django 4.1.4 on 2022-12-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0002_resume_cv_cover_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('page', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('status', models.CharField(choices=[('basic', 'basic'), ('premium', 'premium')], max_length=255)),
            ],
        ),
    ]
